services:
  - type: web
    name: employeemng-backend
    env: python
    rootDir: backend/employeemng
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate && gunicorn employeemng.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: employeemng-backend.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://employeemng-frontend.onrender.com

  - type: web
    name: employeemng-frontend
    env: static
    rootDir: frontend/employee-management
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_BASE_URL
        value: https://employeemng-backend.onrender.com/api
